<?php

namespace Proxies\__CG__\HologramBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Payment extends \HologramBundle\Entity\Payment implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'HologramBundle\\Entity\\Payment' . "\0" . 'idproduct', '' . "\0" . 'HologramBundle\\Entity\\Payment' . "\0" . 'iduser', '' . "\0" . 'HologramBundle\\Entity\\Payment' . "\0" . 'prix', '' . "\0" . 'HologramBundle\\Entity\\Payment' . "\0" . 'ExpirationDate', '' . "\0" . 'HologramBundle\\Entity\\Payment' . "\0" . 'cardnumber', '' . "\0" . 'HologramBundle\\Entity\\Payment' . "\0" . 'verification', '' . "\0" . 'HologramBundle\\Entity\\Payment' . "\0" . 'dateDeb', '' . "\0" . 'HologramBundle\\Entity\\Payment' . "\0" . 'heureDeb', '' . "\0" . 'HologramBundle\\Entity\\Payment' . "\0" . 'heureFin', '' . "\0" . 'HologramBundle\\Entity\\Payment' . "\0" . 'id'];
        }

        return ['__isInitialized__', '' . "\0" . 'HologramBundle\\Entity\\Payment' . "\0" . 'idproduct', '' . "\0" . 'HologramBundle\\Entity\\Payment' . "\0" . 'iduser', '' . "\0" . 'HologramBundle\\Entity\\Payment' . "\0" . 'prix', '' . "\0" . 'HologramBundle\\Entity\\Payment' . "\0" . 'ExpirationDate', '' . "\0" . 'HologramBundle\\Entity\\Payment' . "\0" . 'cardnumber', '' . "\0" . 'HologramBundle\\Entity\\Payment' . "\0" . 'verification', '' . "\0" . 'HologramBundle\\Entity\\Payment' . "\0" . 'dateDeb', '' . "\0" . 'HologramBundle\\Entity\\Payment' . "\0" . 'heureDeb', '' . "\0" . 'HologramBundle\\Entity\\Payment' . "\0" . 'heureFin', '' . "\0" . 'HologramBundle\\Entity\\Payment' . "\0" . 'id'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Payment $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setIdproduct($idproduct)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdproduct', [$idproduct]);

        return parent::setIdproduct($idproduct);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdproduct()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdproduct', []);

        return parent::getIdproduct();
    }

    /**
     * {@inheritDoc}
     */
    public function setIduser($iduser)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIduser', [$iduser]);

        return parent::setIduser($iduser);
    }

    /**
     * {@inheritDoc}
     */
    public function getIduser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIduser', []);

        return parent::getIduser();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrix($prix)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrix', [$prix]);

        return parent::setPrix($prix);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrix()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrix', []);

        return parent::getPrix();
    }

    /**
     * {@inheritDoc}
     */
    public function setVerification($verification)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVerification', [$verification]);

        return parent::setVerification($verification);
    }

    /**
     * {@inheritDoc}
     */
    public function getVerification()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVerification', []);

        return parent::getVerification();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getExpirationDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExpirationDate', []);

        return parent::getExpirationDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setExpirationDate($ExpirationDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExpirationDate', [$ExpirationDate]);

        return parent::setExpirationDate($ExpirationDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getCardnumber()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCardnumber', []);

        return parent::getCardnumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setCardnumber($cardnumber)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCardnumber', [$cardnumber]);

        return parent::setCardnumber($cardnumber);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateDeb()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateDeb', []);

        return parent::getDateDeb();
    }

    /**
     * {@inheritDoc}
     */
    public function getHeureDeb()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHeureDeb', []);

        return parent::getHeureDeb();
    }

    /**
     * {@inheritDoc}
     */
    public function getHeureFin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHeureFin', []);

        return parent::getHeureFin();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateDeb($dateDeb)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateDeb', [$dateDeb]);

        return parent::setDateDeb($dateDeb);
    }

    /**
     * {@inheritDoc}
     */
    public function setHeureDeb($heureDeb)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHeureDeb', [$heureDeb]);

        return parent::setHeureDeb($heureDeb);
    }

    /**
     * {@inheritDoc}
     */
    public function setHeureFin($heureFin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHeureFin', [$heureFin]);

        return parent::setHeureFin($heureFin);
    }

}
