hologram_homepage:
    path:     /
    defaults: { _controller: HologramBundle:Default:indexx }
hologram_signUp:
    path:     /register
    defaults: { _controller: HologramBundle:Default:registerRedirect }
hologram_profile:
    path:     /profile
    defaults: { _controller: HologramBundle:Default:profileRedirect }
hologram_homepagee:
    path:     /index
    defaults: { _controller: HologramBundle:Default:indexx }
    
user_payement:
     path:     /payer/{id}
     defaults: { _controller: HologramBundle:Default:paiement } 
     
esprit_hologram :
     path:     /holog
     defaults: { _controller: HologramBundle:Product:affichage }
esprit_hologram_view_one_product :
     path:     /viewoneprod/{id}
     defaults: { _controller: HologramBundle:Product:viewOneProduct }   
esprit_hologram_refuse_product :
     path:     /refuseprod/{id}
     defaults: { _controller: HologramBundle:Product:refuseProduct }
esprit_hologram_validatate_product :
     path:     /valiaterprod/{id}
     defaults: { _controller: HologramBundle:Product:validateProduct }
esprit_hologram_front_products:
     path:     /products
     defaults: { _controller: HologramBundle:Product:viewProducts }
esprit_hologram_front_final_products:
     path:     /finalp
     defaults: { _controller: HologramBundle:Product:viewFinalProducts }
esprit_hologram_add_product:
     path:     /add
     defaults: { _controller: HologramBundle:Product:addProduct }
esprit_hologram_view_product:
     path:     /view/{id}
     defaults: { _controller: HologramBundle:Product:viewProduct }
esprit_hologram_update_product:
     path:     /update/{id}
     defaults: { _controller: HologramBundle:Product:editProduct }
esprit_hologram_view_validate_products:
     path:     /validprods
     defaults: { _controller: HologramBundle:Product:viewValidateProducts }
esprit_hologram_view_validate_product_back:
     path:     /oneProd/{id}
     defaults: { _controller: HologramBundle:Product:viewOneValidProduct }
esprit_hologram_view_video:
     path:     /vid/{id}
     defaults: { _controller: HologramBundle:Product:viewVideo }
stat:
     path:     /stat/{id}
     defaults: { _controller: HologramBundle:Statistique:stat }